import { Resident } from '../types/report';

export const INITIAL_RESIDENTS: Resident[] = [
  {
    id: 'res-001',
    name: '佐藤 敏子',
    kana: 'サトウ トシコ',
    roomNumber: '201号室',
    gender: 'female',
    birthDate: '1938-04-15',
    age: 88,
    careLevel: '要介護2',
    notes: '立ち上がり時のふらつきあり・要見守り',
  },
  {
    id: 'res-002',
    name: '田中 勇',
    kana: 'タナカ イサム',
    roomNumber: '205号室',
    gender: 'male',
    birthDate: '1941-11-20',
    age: 84,
    careLevel: '要介護3',
    notes: '夜間頻尿・ポータブルトイレ使用',
  },
  {
    id: 'res-003',
    name: '小林 ハツエ',
    kana: 'コバヤシ ハツエ',
    roomNumber: '102号室',
    gender: 'female',
    birthDate: '1934-08-05',
    age: 92,
    careLevel: '要介護4',
    notes: '車椅子自走・皮膚脆弱性あり',
  },
  {
    id: 'res-004',
    name: '渡辺 健一',
    kana: 'ワタナベ ケンイチ',
    roomNumber: '302号室',
    gender: 'male',
    birthDate: '1946-06-18',
    age: 80,
    careLevel: '要介護1',
    notes: '食事時とろみ中濃度',
  },
  {
    id: 'res-005',
    name: '松本 よし',
    kana: 'マツモト ヨシ',
    roomNumber: '208号室',
    gender: 'female',
    birthDate: '1937-02-12',
    age: 89,
    careLevel: '要介護2',
    notes: '夕暮れ症候群による帰宅願望あり',
  },
  {
    id: 'res-006',
    name: '高橋 正夫',
    kana: 'タカハシ マサオ',
    roomNumber: '105号室',
    gender: 'male',
    birthDate: '1939-09-03',
    age: 87,
    careLevel: '要介護3',
    notes: '歩行器使用・右片麻痺軽度',
  },
  {
    id: 'res-007',
    name: '伊藤 キヨ',
    kana: 'イトウ キヨ',
    roomNumber: '203号室',
    gender: 'female',
    birthDate: '1942-01-30',
    age: 84,
    careLevel: '要介護2',
    notes: '排泄時急変注意・血圧変動あり',
  },
  {
    id: 'res-008',
    name: '山本 芳雄',
    kana: 'ヤマモト ヨシオ',
    roomNumber: '301号室',
    gender: 'male',
    birthDate: '1935-12-10',
    age: 90,
    careLevel: '要介護4',
    notes: '全介助・リクライニング車椅子',
  },
  {
    id: 'res-009',
    name: '中村 静江',
    kana: 'ナカムラ シズエ',
    roomNumber: '108号室',
    gender: 'female',
    birthDate: '1944-05-22',
    age: 82,
    careLevel: '要介護1',
    notes: '独歩可能・つまずき注意',
  },
  {
    id: 'res-010',
    name: '斎藤 昇',
    kana: 'サイトウ ノボル',
    roomNumber: '207号室',
    gender: 'male',
    birthDate: '1940-07-14',
    age: 86,
    careLevel: '要介護3',
    notes: '排便時いきみ・意識消失リスクあり',
  },
];
