import { Report } from '../types/report';

export const INITIAL_SAMPLE_REPORTS: Report[] = [
  {
    id: 'report-demo-1',
    type: 'hiyari',
    residentName: '佐藤 敏子',
    gender: 'female',
    birthDate: '1938-04-15',
    age: 88,
    careLevel: '要介護2',
    roomNumber: '201号室',
    reportDate: '2026-09-28',
    dayOfWeek: '月',
    occurrenceDate: '2026-09-28',
    occurrenceTimeOnly: '12:15',
    occurrenceTimeSlot: '昼食前後',
    occurrenceTime: '12:15 (昼食前後)',
    location: '食堂',
    locationDetail: '配膳カウンター前、テーブル3番付近',
    situationCategory: '転倒・転落',
    situationDescription: '昼食配膳時、利用者様が自席から立ち上がって車椅子から歩行器へ乗り移ろうとした際、足元がおぼつかず後方にバランスを崩しかけた。背後にいた職員がすぐに駆け寄って支え、転倒を未然に回避した。怪我なし。',
    factorsPersonalTags: ['焦り・慌ただしさ', 'コール対応中'],
    factorsPersonal: '昼食配膳のピーク時で職員がトレイ運搬や他の見守りに追われており、立ち上がりの予兆への声かけが数秒遅れた。本人様はお茶を自分で注ぎに行こうと急がれていた。',
    factorsMaterialTags: [],
    factorsMaterial: '車椅子の左側フットブレーキの固定具がやや緩んでおり、立ち上がり時に車輪がわずかに後ろへ動いたためバランスを崩しやすかった。',
    factorsEnvironmentalTags: ['導線混雑時'],
    factorsEnvironmental: '配膳カートと下膳待ちのワゴンで食堂中央の通路が狭くなっており、死角が生まれていた。また給茶機付近の床に水滴がわずかに飛び散っていた。',
    emergencyResponse: '職員が両腕で体を保持し、直ちに椅子に着席していただいた。バイタル測定（血圧128/76、脈拍74）、外傷・疼痛の有無を確認し異常なし。ご本人に「お茶はお持ちしますのでいつでも呼んでくださいね」と優しく声かけ。',
    preventiveMeasures: '・車椅子のブレーキワイヤー調整を実施し、全車椅子の週次点検表にチェック。\n・昼食配膳時はテーブル担当のフリー職員を1名固定配置し、立ち上がり見守りを専従化。\n・給茶機周辺に吸水滑り止めマットを設置。',
    reporterName: '高橋 涼介',
    supervisorComment: '素早い対応で怪我に至らず良かったです。車輪ブレーキの緩みは点検ルーティンに直ちに追加しました。動線の改善もフロアミーティングで共有済。',
    supervisorConfirmed: true,
    status: 'resolved',
    severity: 'level0',
    createdAt: '2026-09-28T12:45:00.000Z',
    updatedAt: '2026-09-28T17:30:00.000Z',
  },
  {
    id: 'report-demo-2',
    type: 'hiyari',
    residentName: '田中 勇',
    gender: 'male',
    birthDate: '1941-11-20',
    age: 84,
    careLevel: '要介護3',
    roomNumber: '205号室',
    reportDate: '2026-09-27',
    dayOfWeek: '日',
    occurrenceDate: '2026-09-27',
    occurrenceTimeOnly: '02:30',
    occurrenceTimeSlot: '夜中',
    occurrenceTime: '02:30 (夜中)',
    location: '居室内',
    locationDetail: '205号室 ベッド脇',
    situationCategory: '転倒・転落',
    situationDescription: '午前2時30分の夜間定期巡回時、205号室ベッドサイドにて、田中様がベッド柵を外して端座位になっており、ポータブルトイレへ自力移乗しようと両手を伸ばしていた。足元がスリッパから外れて床に滑りそうになっていたところを巡回職員が発見、転倒を防いだ。',
    factorsPersonalTags: ['不穏・認知症状', '身体機能の急変・ふらつき'],
    factorsPersonal: 'ご本人様は「トイレに行かなければ」と強い尿意を感じて焦っておられた。夜間の覚醒で軽度の見当識低下あり。',
    factorsMaterialTags: ['靴サイズの不適合・足踏み'],
    factorsMaterial: 'ナースコールのコードがシーツの隙間に挟まって垂れ下がっており、ご本人の手の届く範囲になかった。またスリッパのかかとを踏んで履かれていた。',
    factorsEnvironmentalTags: ['見守り時間外'],
    factorsEnvironmental: 'フットセンサーマットの電源スイッチが掃除の際に切れたままになっており、コールがナースステーションに飛ばなかった。室内常夜灯が暗く足元が見えにくかった。',
    emergencyResponse: '排泄介助を実施（失禁なし、ポータブルトイレにて排尿成功）。靴を履き替えさせ、水分補給を行って安眠を促した。バイタル安定。',
    preventiveMeasures: '・夜勤申し送り時に全居室のセンサーマット通電チェックを必ず2名で読み合わせ確認する。\n・夜間用の足元フットライト（人感センサー付き）をベッド足元に増設。\n・かかとが固定できるリハビリ介護シューズの着用をご家族に相談し手配。',
    reporterName: '中村 美保',
    supervisorComment: 'センサーマットの電源オフ見逃しは重大事故に直結する可能性がありました。チェックリストにダブルチェック項目を新設し徹底します。',
    supervisorConfirmed: true,
    status: 'resolved',
    severity: 'level0',
    createdAt: '2026-09-27T03:10:00.000Z',
    updatedAt: '2026-09-27T10:00:00.000Z',
  },
  {
    id: 'report-demo-3',
    type: 'accident',
    residentName: '小林 ハツエ',
    gender: 'female',
    birthDate: '1934-08-05',
    age: 92,
    careLevel: '要介護4',
    roomNumber: '102号室',
    reportDate: '2026-09-26',
    dayOfWeek: '土',
    occurrenceDate: '2026-09-26',
    occurrenceTimeOnly: '10:15',
    occurrenceTimeSlot: '午前中',
    occurrenceTime: '10:15 (午前中)',
    location: '廊下',
    locationDetail: 'エレベーターホール前、手すり沿い',
    situationCategory: '皮膚剥離・打撲・外傷',
    situationDescription: '車椅子自走にてレクリエーション会場へ移動中、エレベーター前の壁面掲示板のアルミ枠角に左前腕部を擦り付け、表皮剥離（約2cm×1cm、少量の滲出液・出血）が発生した。',
    factorsPersonalTags: ['確認漏れ・思い込み'],
    factorsPersonal: '自走のスピードがやや速く、周囲の曲がり角への注意が散漫になっていた。皮膚が脆弱（ステロイド外用歴あり）。',
    factorsMaterialTags: [],
    factorsMaterial: '長袖の袖口をめくっていたため、直接皮膚が突起部に接触してしまった。',
    factorsEnvironmentalTags: ['坂道・段差'],
    factorsEnvironmental: '掲示板のアルミフレーム下部に保護クッションが貼られておらず、金属の鋭利なエッジが露出していた。',
    emergencyResponse: '施設看護師へ即時連絡。生理食塩水にて創部洗浄、ハイドロコロイド被覆材で処置。止血確認。ご家族へ電話連絡し状況と処置内容を報告・了解を得る。',
    preventiveMeasures: '・施設内全域の壁面掲示板・柱の角部（床上80cm〜120cmの車椅子接触高）にウレタン製コーナークッションを即日貼付。\n・皮膚脆弱な利用者様のアームカバー着用をケアプランに追記。',
    reporterName: '木村 拓也',
    supervisorComment: '看護師の迅速な処置とご家族への丁寧な連絡が適切でした。コーナークッションは施設全体で点検完了しました。',
    supervisorConfirmed: true,
    status: 'reviewing',
    severity: 'level1',
    createdAt: '2026-09-26T10:30:00.000Z',
    updatedAt: '2026-09-26T16:00:00.000Z',
  },
  {
    id: 'report-demo-4',
    type: 'hiyari',
    residentName: '斎藤 昇',
    gender: 'male',
    birthDate: '1940-07-14',
    age: 86,
    careLevel: '要介護3',
    roomNumber: '207号室',
    reportDate: '2026-09-25',
    dayOfWeek: '金',
    occurrenceDate: '2026-09-25',
    occurrenceTimeOnly: '14:20',
    occurrenceTimeSlot: '午後',
    occurrenceTime: '14:20 (午後)',
    location: 'トイレ',
    locationDetail: '2階南側トイレ内',
    situationCategory: '意識消失・便ショック',
    situationDescription: 'トイレ排便時、強く息んだ直後に一時的な顔面蒼白と眼前暗黒感（血管迷走神経反射様症状）を訴え、便座から前方に崩れ落ちそうになった。同行見守り職員が前額部と肩を保持し、床への転倒を防御した。約1分後に意識清明、バイタル測定。',
    factorsPersonalTags: ['身体機能の急変・ふらつき', '体調不良・倦怠感'],
    factorsPersonal: '水分摂取量がやや少なめで便が硬く、過度の腹圧（息み）がかかった。',
    factorsMaterialTags: [],
    factorsMaterial: 'トイレ内の前方支持バーがやや遠く、前傾保持が不安定だった。',
    factorsEnvironmentalTags: ['マニュアルの不備'],
    factorsEnvironmental: '排便見守り時の手順（息みすぎ防止の声かけ）が新人に十分に共有されていなかった。',
    emergencyResponse: '下肢挙上し安静臥床、看護師によるバイタルチェック（BP 98/58、HR 56徐脈からBP 118/70、HR 68へ回復）。医師へ報告し経過観察。',
    preventiveMeasures: '・排便時の水分摂取プランと緩下剤の処方見直しを看護師・嘱託医と連携。\n・排便介助時の「息み・便ショック注意喚起」を申し送りノートに追記。',
    reporterName: '佐々木 遥',
    supervisorComment: '素早い保持で転倒や頭部打撲を未然に防いだ好事例です。便ショックは高齢者施設で多発するため、全職員に勉強会で周知します。',
    supervisorConfirmed: true,
    status: 'resolved',
    severity: 'level0',
    createdAt: '2026-09-25T14:40:00.000Z',
    updatedAt: '2026-09-25T17:00:00.000Z',
  },
  {
    id: 'report-demo-5',
    type: 'hiyari',
    residentName: '松本 よし',
    gender: 'female',
    birthDate: '1937-02-12',
    age: 89,
    careLevel: '要介護2',
    roomNumber: '208号室',
    reportDate: '2026-09-24',
    dayOfWeek: '木',
    occurrenceDate: '2026-09-24',
    occurrenceTimeOnly: '16:45',
    occurrenceTimeSlot: '夕方',
    occurrenceTime: '16:45 (夕方)',
    location: 'デイサービスフロア',
    locationDetail: 'デイルーム出入口前',
    situationCategory: '離設・徘徊・無断外出',
    situationDescription: '帰宅送迎前の時間帯、「家に帰ってご飯を作らなきゃ」と荷物を持って玄関自動ドアに向かって歩行器で進んでいるところを発見。職員が笑顔で声かけを行い、フロア内のソファへ誘導した。',
    factorsPersonalTags: ['不穏・認知症状', '焦り・慌ただしさ'],
    factorsPersonal: '夕方の薄暮時間帯（夕暮れ症候群）による不安感の高まりと帰宅願望。',
    factorsMaterialTags: ['歩行器・杖の不具合'],
    factorsMaterial: '歩行器のブレーキロックが甘い状態のまま歩行されていた。',
    factorsEnvironmentalTags: ['見守り時間外', '導線混雑時'],
    factorsEnvironmental: '送迎車の準備でフロア内の職員が一時的に減り、出入口付近の見守りが手薄になっていた。',
    emergencyResponse: '「美味しいお茶を淹れましたので、一息つきませんか？」と受容的対応。温かい麦茶とアルバムを一緒に見ながら傾聴し、落ち着きを取り戻された。',
    preventiveMeasures: '・夕暮れ時の出入口ロック施錠確認ルーティン。\n・送迎準備中もフロア見守り担当1名を必ず常駐。\n・玄関マットにチャイムセンサーを再設置。',
    reporterName: '小林 誠',
    supervisorComment: '受容的なお声かけで不安を和らげた対応が素晴らしいです。玄関の鍵管理は送迎チェックリストに組み込みました。',
    supervisorConfirmed: true,
    status: 'resolved',
    severity: 'level0',
    createdAt: '2026-09-24T16:15:00.000Z',
    updatedAt: '2026-09-24T17:45:00.000Z',
  }
];
